version: "3.8"

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
    networks:
      - webnet

  php-fpm:
    build: docker/php-fpm
    volumes:
      - ./src:/var/www/html
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: "1370"
